# -*- coding: utf-8 -*-
"""IMAGE_TO_PENCIL_SKETCH_PROJECT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/DevlinaPal/LGMVIP-DataScience/blob/main/Beginner-level/IMAGE%20TO%20PENCIL%20SKETCH%20WITH%20PYTHON/IMAGE_TO_PENCIL_SKETCH_PROJECT.ipynb

NAME- RAJ KAMAL SHAKYA

LGM-VIP INTERNSHIP

 BEGINNER LEVEL TASK -4

 Image to Pencil Sketch with Python

1. IMPORT LIBRARY
"""

# Commented out IPython magic to ensure Python compatibility.
import  cv2
import matplotlib.pyplot as plt
# %matplotlib inline

def show(title,img,cmap='RdBu'):
    plt.imshow(img,cmap=cmap)
    plt.title(title)

"""2. IMAGE LOADING"""

image=plt.imread("cat.jpg")
show("cat",image,'RdBu')
#cv2.imshow("Cat",image)
#cv2.waitKey(0)

"""3. CONVERT TO GRAYSCALE IMAGE"""

#convert to grayscale image
gray_image=cv2.cvtColor(image,cv2.COLOR_RGB2GRAY)
show("gray_image",gray_image,'gray')
#cv2.imshow("gray_image",gray_image)
#cv2.waitKey(0)

"""4. INVERT THE GRAYSCALE IMAGE"""

#invert the grayscale image
inverted_image =255-gray_image
show("inverted_image",inverted_image,'gray')
#cv2.imshow("inverted_image",inverted_image)
#cv2.waitKey(0)

"""5. BLUR THE INVERTED IMAGE"""

#blur the inverted image
blurred_image =cv2.GaussianBlur(inverted_image,(21,21),0)
show("blurred_image",blurred_image,'gray')
#cv2.imshow("blurred_image",blurred_image)
#cv2.waitKey(0)

"""6. CREATE PENCIL SKETCH IMAGE"""

inverted_blurred=255-blurred_image
pencil_sketch=cv2.divide(gray_image,inverted_blurred,scale=256.0)
show("pencil_sketch",pencil_sketch,'gray')